# config class for models loading
# model_name:
#   path: "path to model"
#   class: "wrapper class"

token_classification:
  path: "/data/trained_model.nemo"
  class: TokenClassificationWrapper
sapbert:
  path: "/data/SapBERT-from-PubMedBERT-fulltext"
  class: SapbertWrapper
  storage: "qdrant"
#   If using elasticsearch use the following connection parameters
#   storage: "elasticsearch"
#   connectionParams:
#     host: "http://localhost:9200"
#     username: "elastic"
#     password: ""
#     index: "sap_index"
  connectionParams:
    host: "localhost"
    port: 6333
    password: ""
    index: "sap_index"
  ground_truth_predictions_path: "/data/pubmed_mesh_prediction_output.npy"
  ground_truth_id_name_pairs_path: "/data/pubmed_mesh_name_ids.csv"
  ground_truth_data_id_type_pairs_path: "/data/pubmed_mesh_name_types.csv"